# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  username: inventuser
  password: yA*4(682bhL
  host: localhost
#  encoding: utf8mb4
#  collation: utf8mb4_unicode_ci

development:
  <<: *default
  database: inv_dev
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

test:
  <<: *default
  database: inv_test
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

production:
  <<: *default
  database: inv
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
